### PR TITLE
Shopping list

### PR DESCRIPTION
**Pull request by itrevex**

### CODE REVIEW

**Comment by itrevex** [comment]
@serubirikenny
@ruganda
@daud1
@CeciliaCaroline
@Sebuliba-Adrian

Please review when you find time, any feedback will be appreciated

**Comment by Sebuliba-Adrian** [comment]
I have reviewed your code. I see its going on well. Just need to fix the failing CI

**Comment by ruganda** [comment]
its good work only need to configure the danger sign on travis ci

**Comment by Descartess** [comment]
Great tests and great use of doc style comments. I recommend using of a .gitignore file so that git ignores irrelevant files in the structure  like __pycache__. Travis is failing because theres no .travis.yml in this branch . I recommend further branches be made from working branches like master or other working branches. 

Finally change your readme file from .txt to .md to take advantage of the markdown supported syntaxes

**Comment by CeciliaCaroline** [comment]
Good comments.
Code is well organized
Add cache files to git ignore
Add requirements.txt file

**Pull request merged**
