### PR TITLE
Login

### PR DESCRIPTION
**Pull request by itrevex**

### CODE REVIEW

**Comment by itrevex** [comment]
please login class for shopping list app @descartess, @JoyLubega, @serubirikenny

**Comment by serubirikenny** [comment]
The use of Docstrings and Comments makes the code very organised and very readable.

**Comment by JoyLubega** [comment]
login is just a function, why do you call it a class?
And your readme looks ignored dear

**Comment by itrevex** [comment]
Thanks, let work on it

**Pull request merged**
